---
title: "Setup"
author: "Reuben Perez"
date: "5/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 1) Set Up

```{r cars}
# remove all objects
rm(list=ls())

# Unload all packages 
library(pacman)
pacman::p_unload(all)

#Load packages
pacman::p_load(
  tidyverse, #dplyr, readr, etc.
  data.table, #fread() 
  foreign, #load data types including stata .dta files
  haven, #read STATA files
  magrittr, #%<>% operator
  skimr, #for summerising
)
```

# 2) Import STATA File 

```{r}
setwd('/Users/Reubenperez/Dropbox/R Projects/Latinx Project')

Latinx <- read_dta("Latinx.dta")
```

# 3) Create Dependent Variable 

```{r}
# Create binary variable for use of Latinx/Hispanic Label. 
Latinx_Panethnic <- character (0)

#Fill in values for Latinx/Hispanic Label 
Latinx_Panethnic[Latinx$Q24a %in% c("1","2","3") | Latinx$Q24b %in% c("1","2","3") | Latinx$Q24c %in% c("1","2","3") ] <- 1
Latinx_Panethnic[Latinx$Q24a %in% "4" | Latinx$Q24b %in% "4" | Latinx$Q24c %in% "4"] <- 0 
```

# 4) Create Independent Variables

```{r}
# Create categorical variable for Education. 
Education <- character (0)

#Create Education Variable
Education [Latinx$Q20 %in% c("1","2")] <- 1 #less than HS
Education[Latinx$Q20 %in% "3"] <- 2 #High School
Education[Latinx$Q20 %in% c("5", "6")] <-3 #Some College/Associates
Education[Latinx$Q20 %in% "7"] <- 4 #Bachelors
Education [Latinx$q20 %in% "8"] <- 5 #Post Grad

#Add Labels to values
Education <- factor(Education, levels = c(1,2,3,4,5), 
                    labels = c("Less than HS", "High School", "Some College or Associates", "Bachelors", "Post Graduate")) 

#Create Generation Variable
Immigrant_Generation <- character(0)

#Create Education Variable
Immigrant_Generation[Latinx$Q26 %in% "2"] <- 1 #Foreign born/first gen
Immigrant_Generation[Latinx$Q26 %in% "1" & Latinx$Q27 %in% "1"] <- 2 #secong gen
Immigrant_Generation[Latinx$Q26 %in% "1" & Latinx$Q27 %in% "3"] <- 3 #Third gen


#Add Labels to values
Immigrant_Generation <- factor(Immigrant_Generation, levels = c(1,2,3), 
                    labels = c("First Generation", "Second Generation", "Third Generation")) 


#Create Variable Household Income
HouseholdIncome <- as.numeric(Latinx$Q35)

#Create Gender Variable 
gender <- character(0)

#Fill in Values
gender [Latinx$Q18 %in% "2"] <-0 #men
gender [Latinx$Q18 %in% "1"] <-1 #women
 
#Create Ethnicity variable
Ethnicity <- character (0)

#Fill in values
Ethnicity[Latinx$Q23_1 %in% "1"] <- 1
Ethnicity[Latinx$Q23_3 %in% "1"] <- 2
Ethnicity[Latinx$Q23_5 %in% "1"] <- 3
Ethnicity[Latinx$Q23_2 %in% "1" | Latinx$Q23_4 %in% "1" | Latinx$Q23_6 %in% "1"] <- 4

#Add Labels to values
Ethnicity <- factor(Ethnicity, levels = c(1,2,3,4),
                    labels = c("Mexican", "Central American", "South American","Other"))


#Create age cohort variables 
Latinx %<>%
  mutate(gen_boomer = ifelse(AGE > "54", "1", "0")) %>%
  mutate(gen_x = ifelse(AGE >= "38" & AGE < "55" , "1", "0")) %>%
  mutate(gen_millenial = ifelse(AGE <= "37" & AGE >= "26", "1","0")) %>%
  mutate(gen_z = ifelse(AGE < "26", "1", "0"))


#Generate New varibale (age cohorts)
cohorts <- character(0)

#Fill in values
cohorts[Latinx$gen_boomer %in% "1"] <-1
cohorts[Latinx$gen_x %in% "1"] <-2
cohorts[Latinx$gen_millenial %in% "1"] <-3
cohorts[Latinx$gen_z %in% "1"] <-4

#Add labels to values
cohorts <- factor(cohorts, levels = c(1,2,3,4),
                    labels = c("boomers", "genx", "millenials", "genz"))

#Create politics Label
Political_leanings <- character(0)

#Fill in Values
Political_leanings [Latinx$Q30 %in% "1" |Latinx$Q30 %in% "2" ] <- 1 #Conservative
Political_leanings [Latinx$Q30 %in% "3"] <- 2 #Moderate
Political_leanings [Latinx$Q30 %in% "4" | Latinx$Q30 %in% "5"] <- 3 #Liberal 

#Add labels to values
Political_leanings <- factor(Political_leanings, levels = c(1,2,3), labels = c("Conservative", "Moderate","Liberal"))

```

# 5) Add Variables to Dataset Using Cbind

```{r}

#Add variables to dataset
Latinx <- cbind(Latinx, Latinx_Panethnic)
Latinx <- cbind(Latinx, Immigrant_Generation)
Latinx <- cbind(Latinx, Education)
Latinx <- cbind(Latinx, HouseholdIncome)
Latinx <- cbind(Latinx, gender)
Latinx <- cbind(Latinx, cohorts)
Latinx <- cbind(Latinx, Political_leanings)
Latinx <- cbind(Latinx, Race)

```

# 6) Subset Latinx Dataset with New Variables for Analysis 

```{r}

#Create DF with variables to analyze

Latinx_subset <- Latinx %>% select(Latinx_Panethnic, Immigrant_Generation,Education, HouseholdIncome, Political_leanings)

view(Latinx_subset)

#Save as csv
write.csv(Latinx_subset,'Latinx_subset.csv')
```

